name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Directory Permissions
        run: |
          chmod -R 755 storage bootstrap/cache
          chmod -R 644 database/database.sqlite
          php artisan key:generate --no-interaction
          php artisan config:cache
          mkdir -p database
          touch database/database.sqlite
          chmod -R 775 database
          php artisan migrate --no-interaction --force

      - name: Execute tests (Unit and Feature tests) via PHPUnit
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: ${{ github.workspace }}/database/database.sqlite
        run: vendor/bin/phpunit
