name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Directory Permissions
        run: |
          mkdir -p bootstrap/cache
          mkdir -p storage/app/public
          mkdir -p storage/framework/{cache,sessions,testing,views}
          mkdir -p storage/logs
          chmod -R 777 storage bootstrap/cache

      - name: Clear Cache
        run: php artisan cache:clear

      - name: Clear Config Cache
        run: php artisan config:clear

      - name: Generate key
        run: php artisan key:generate

      - name: Set up SQLite Database
        run: |
          mkdir -p database
          touch database/database.sqlite
          php artisan migrate --no-interaction --force

      - name: Execute tests (Unit and Feature tests) via PHPUnit
        run: vendor/bin/phpunit
