name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Directory Permissions
        run: |
          mkdir -p bootstrap/cache
          mkdir -p storage/app/public
          mkdir -p storage/framework/{cache,sessions,testing,views}
          mkdir -p storage/logs
          chmod -R 777 storage
          chmod -R 777 bootstrap/cache
      - name: Prepare SQLite database
        run: |
          touch database/database.sqlite
          cp .env.example .env
          sed -i 's/DB_CONNECTION=mysql/DB_CONNECTION=sqlite/g' .env
          sed -i 's/DB_HOST=mysql
          DB_PORT=3306
          DB_DATABASE=laraval
          DB_USERNAME=root
          DB_PASSWORD=/DB_CONNECTION=sqlite/g' .env
      - name: Generate key
        run: php artisan key:generate --no-interaction
      - name: Run database migrations
        run: php artisan migrate --no-interaction
      - name: Run (Unit and Feature) Tests
        run: vendor/bin/phpunit
